import { formatHouse, formatZodiacSign } from '../../../visualProfileConfig';
import HouseEnvironmentLayer from '../../environment/HouseEnvironmentLayer';
import { CENTER, SignTextureLayer, transformationStyle } from '../shared';
import type { MarsGeometryProps } from '../types';

export default function MarsGeometry({ parameter, environment, transformation, instanceId = '', relationSnapshot = false }: MarsGeometryProps) {
  const signLabel = formatZodiacSign(parameter.sign);
  const houseLabel = formatHouse(parameter.house).toLowerCase();
  const vectorRotation = relationSnapshot ? 0 : (transformation.polarity.direction === 'outward' ? -8 : 7) + transformation.modality.variation * 9;
  const vectorScale = relationSnapshot ? 1 : 0.92 + (transformation.polarity.spread - 0.82) * 0.35;
  return (
    <svg className="visual-profile-prototype__svg visual-profile-prototype__svg--mars" viewBox="0 0 480 480" role="img" style={relationSnapshot ? undefined : transformationStyle(transformation)} data-direction={relationSnapshot ? undefined : transformation.polarity.direction} data-texture={relationSnapshot ? undefined : transformation.element.texture} aria-labelledby="visual-profile-mars-title visual-profile-mars-description">
      <title id="visual-profile-mars-title">Mars in {signLabel} in the {houseLabel}</title><desc id="visual-profile-mars-description">A compressed and persistent fluid vector held within a dense, stable and grounded field.</desc>
      <defs><radialGradient id="visual-profile-held-field" cx="50%" cy="64%" r="55%"><stop offset="0%" stopColor="#8edbea" stopOpacity="0.13" /><stop offset="58%" stopColor="#557ca8" stopOpacity="0.055" /><stop offset="100%" stopColor="#07101d" stopOpacity="0" /></radialGradient><linearGradient id="visual-profile-ground-layer" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#87c9d8" stopOpacity="0.07" /><stop offset="100%" stopColor="#26394f" stopOpacity="0.015" /></linearGradient><linearGradient id="visual-profile-mars-vector" x1="0" y1="1" x2="1" y2="0"><stop offset="0%" stopColor="#7099b4" stopOpacity="0.26" /><stop offset="52%" stopColor="#b7eff7" stopOpacity="0.82" /><stop offset="100%" stopColor="#e5fbff" stopOpacity="0.94" /></linearGradient><filter id="visual-profile-mars-glow" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="3" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
      <HouseEnvironmentLayer environment={environment} instanceId={`${parameter.planetId}${instanceId}`} />
      <g id={`visual-profile-planet-layer${instanceId}`} aria-label="Mars vector and impulse"><g className="visual-profile-mars__counter-vectors"><path d="M 210 271 L 148 322" /><path d="M 204 260 L 132 281" /></g><g className="visual-profile-mars__vector" transform={`translate(${CENTER} ${CENTER}) rotate(${vectorRotation}) scale(${vectorScale}) translate(${-CENTER} ${-CENTER})`}><path className="visual-profile-mars__vector-rail" d="M 200 280 C 229 249, 257 221, 314 163" /><path className="visual-profile-mars__vector-rail" d="M 214 294 C 246 264, 276 235, 329 179" /><path className="visual-profile-mars__vector-core" d="M 206 287 C 239 256, 270 225, 322 171" /><path className="visual-profile-mars__vector-tip" d="M 306 160 L 339 151 L 330 184 Z" /></g><ellipse className="visual-profile-mars__compressed-halo" cx="207" cy="286" rx="38" ry="30" transform="rotate(-38 207 286)" /><circle className="visual-profile-mars__compressed-core" cx="207" cy="286" r="12" /><circle className="visual-profile-mars__core-ring" cx="207" cy="286" r="22" /></g>
      <g id={`visual-profile-sign-layer${instanceId}`} aria-label={`${signLabel} transformation`} data-polarity={parameter.polarity} data-modality={parameter.modality} data-element={parameter.element}>{relationSnapshot ? <><path className="visual-profile-scorpio__contained-flow" d="M 105 235 C 144 174, 219 179, 245 228 S 318 308, 376 245" /><path className="visual-profile-scorpio__contained-flow visual-profile-scorpio__contained-flow--inner" d="M 126 253 C 165 209, 214 211, 241 246 S 306 291, 354 258" /><path className="visual-profile-scorpio__return-flow" d="M 349 210 C 314 176, 276 184, 247 215 S 176 256, 129 220" /><ellipse className="visual-profile-scorpio__fixed-orbit" cx={CENTER} cy="247" rx="151" ry="104" /><g className="visual-profile-scorpio__anchors"><circle cx="105" cy="235" r="3" /><circle cx="376" cy="245" r="3" /><circle cx="349" cy="210" r="2.5" /><circle cx="129" cy="220" r="2.5" /></g></> : <SignTextureLayer transformation={transformation} />}</g>
      <g id={`visual-profile-label-layer${instanceId}`} aria-label="Prototype label"><text className="visual-profile-label__symbol visual-profile-label__symbol--mars" x="207" y="292">♂</text><text className="visual-profile-label__stage" x={CENTER} y="438">{environment.stageLabel}</text></g>
    </svg>
  );
}
